version: '3'
services:
  mongo:
    image: mongo:${VER_MONGO}
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
  rabbit:
    image: rabbitmq:latest

  search_engine_ui:
    image: vsb2007/search_engine_ui:latest
    environment:
      - MONGO=mongo
    ports:
      - 8000:8000/tcp
    restart: always

  search_engine_crawler:
    image: vsb2007/search_engine_crawler:latest
    ports:
      - 8001:8000/tcp
    restart: always
    depends_on: [rabbit]
    command: https://vitkhab.github.io/search_engine_test_site/
    environment:
      - MONGO=mongo
      - RMQ_HOST=rabbit
      - CHECK_INTERVAL=3600
      - EXCLUDE_URLS='.*github.com'
